### ISSUE TITLE
Rephrase README.md

### ISSUE THREAD

**Issue by godcrampy** [rohitbakoliya/Speech-Recognition#1]
In your ```README.md```, you mention that the speech recognition does not use any APIs but your ```script.js``` file indeed uses the [WebSpeech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API). Please rephrase the readme file.

**Comment by rohitbakoliya** [comment]
My bad...I changed it.
